variable "resource_group_name" {
  type        = string
  description = "Name of the resource group."
}

variable "location" {
  type        = string
  description = "Azure region."
}

variable "project" {
  type        = string
  description = "Project or application name used in resource naming."
}

variable "environment" {
  type        = string
  description = "Deployment environment (dev, staging, prod)."
}

variable "vm_size" {
  type        = string
  default     = "Standard_D2ls_v5"
  description = "VM SKU. Use Standard_B2s as a fallback if Standard_D2ls_v5 is not available in the region."
}

variable "os_disk_size_gb" {
  type        = number
  default     = 64
  description = "OS disk size in GB. 64 GB is sufficient for build tools + Docker images."
}

variable "admin_username" {
  type        = string
  default     = "azureuser"
  description = "SSH admin username for the Linux VM."
}

variable "ssh_public_key" {
  type        = string
  sensitive   = true
  description = "SSH RSA public key (OpenSSH format). Generated by the root module via tls_private_key."
}

variable "subnet_id" {
  type        = string
  description = "Resource ID of the subnet for the VM NIC (snet-vm)."
}

variable "tags" {
  type        = map(string)
  default     = {}
  description = "Resource tags to apply to all resources in this module."
}
