variable "resource_group_name" {
  type        = string
  description = "Name of the resource group."
}

variable "location" {
  type        = string
  description = "Azure region."
}

variable "project" {
  type        = string
  description = "Project name used in resource naming."
}

variable "environment" {
  type        = string
  description = "Deployment environment (dev, staging, prod)."
}

variable "suffix" {
  type        = string
  description = "Random short suffix to ensure globally unique SQL server name."
}

variable "admin_username" {
  type        = string
  default     = "sqladmin"
  description = "SQL Server administrator login name."
}

variable "admin_password" {
  type        = string
  sensitive   = true
  description = "SQL Server administrator password. Generated by random_password in the root module."
}

variable "db_sku" {
  type        = string
  default     = "Basic"
  description = "Database SKU. 'Basic' = 5 DTUs, cheapest option."
}

variable "db_max_size_gb" {
  type        = number
  default     = 2
  description = "Maximum database size in GB. 2 GB is the minimum for Basic tier."
}

variable "aks_subnet_cidr" {
  type        = string
  description = "CIDR of the AKS subnet (e.g. 10.0.1.0/24). Used in SQL firewall rule."
}

variable "vm_subnet_cidr" {
  type        = string
  description = "CIDR of the Build VM subnet (e.g. 10.0.2.0/24). Used in SQL firewall rule."
}

variable "tags" {
  type        = map(string)
  default     = {}
  description = "Resource tags to apply to all resources in this module."
}
